#!/usr/bin/python

### OT specs, from http://www.microsoft.com/typography/otspec/ttoreg.htm

OTfeatures = {
	"aalt": "Access All Alternates",
	"abvf": "Above-base Forms",
	"abvm": "Above-base Mark Positioning",
	"abvs": "Above-base Substitutions",
	"afrc": "Alternative Fractions",
	"akhn": "Akhands",
	"blwf": "Below-base Forms",
	"blwm": "Below-base Mark Positioning",
	"blws": "Below-base Substitutions",
	"calt": "Contextual Alternates",
	"case": "Case-Sensitive Forms",
	"ccmp": "Glyph Composition / Decomposition",
	"cfar": "Conjunct Form After Ro",
	"cjct": "Conjunct Forms",
	"clig": "Contextual Ligatures",
	"cpct": "Centered CJK Punctuation",
	"cpsp": "Capital Spacing",
	"cswh": "Contextual Swash",
	"curs": "Cursive Positioning",
#	"cv01-cv99": "Character Variants",
	"c2pc": "Petite Capitals From Capitals",
	"c2sc": "Small Capitals From Capitals",
	"dist": "Distances",
	"dlig": "Discretionary Ligatures",
	"dnom": "Denominators",
	"expt": "Expert Forms",
	"falt": "Final Glyph on Line Alternates",
	"fin2": "Terminal Forms #2",
	"fin3": "Terminal Forms #3",
	"fina": "Terminal Forms",
	"frac": "Fractions",
	"fwid": "Full Widths",
	"half": "Half Forms",
	"haln": "Halant Forms",
	"halt": "Alternate Half Widths",
	"hist": "Historical Forms",
	"hkna": "Horizontal Kana Alternates",
	"hlig": "Historical Ligatures",
	"hngl": "Hangul",
	"hojo": "Hojo Kanji Forms (JIS X 0212-1990 Kanji Forms)",
	"hwid": "Half Widths",
	"init": "Initial Forms",
	"isol": "Isolated Forms",
	"ital": "Italics",
	"jalt": "Justification Alternates",
	"jp78": "JIS78 Forms",
	"jp83": "JIS83 Forms",
	"jp90": "JIS90 Forms",
	"jp04": "JIS2004 Forms",
	"kern": "Kerning",
	"lfbd": "Left Bounds",
	"liga": "Standard Ligatures",
	"ljmo": "Leading Jamo Forms",
	"lnum": "Lining Figures",
	"locl": "Localized Forms",
	"ltra": "Left-to-right alternates",
	"ltrm": "Left-to-right mirrored forms",
	"mark": "Mark Positioning",
	"med2": "Medial Forms #2",
	"medi": "Medial Forms",
	"mgrk": "Mathematical Greek",
	"mkmk": "Mark to Mark Positioning",
	"mset": "Mark Positioning via Substitution",
	"nalt": "Alternate Annotation Forms",
	"nlck": "NLC Kanji Forms",
	"nukt": "Nukta Forms",
	"numr": "Numerators",
	"onum": "Oldstyle Figures",
	"opbd": "Optical Bounds",
	"ordn": "Ordinals",
	"ornm": "Ornaments",
	"palt": "Proportional Alternate Widths",
	"pcap": "Petite Capitals",
	"pkna": "Proportional Kana",
	"pnum": "Proportional Figures",
	"pref": "Pre-Base Forms",
	"pres": "Pre-base Substitutions",
	"pstf": "Post-base Forms",
	"psts": "Post-base Substitutions",
	"pwid": "Proportional Widths",
	"qwid": "Quarter Widths",
	"rand": "Randomize",
	"rkrf": "Rakar Forms",
	"rlig": "Required Ligatures",
	"rphf": "Reph Forms",
	"rtbd": "Right Bounds",
	"rtla": "Right-to-left alternates",
	"rtlm": "Right-to-left mirrored forms",
	"ruby": "Ruby Notation Forms",
	"salt": "Stylistic Alternates",
	"sinf": "Scientific Inferiors",
	"size": "Optical size",
	"smcp": "Small Capitals",
	"smpl": "Simplified Forms",
	"ss01": "Stylistic Set 1",
	"ss02": "Stylistic Set 2",
	"ss03": "Stylistic Set 3",
	"ss04": "Stylistic Set 4",
	"ss05": "Stylistic Set 5",
	"ss06": "Stylistic Set 6",
	"ss07": "Stylistic Set 7",
	"ss08": "Stylistic Set 8",
	"ss09": "Stylistic Set 9",
	"ss10": "Stylistic Set 10",
	"ss11": "Stylistic Set 11",
	"ss12": "Stylistic Set 12",
	"ss13": "Stylistic Set 13",
	"ss14": "Stylistic Set 14",
	"ss15": "Stylistic Set 15",
	"ss16": "Stylistic Set 16",
	"ss17": "Stylistic Set 17",
	"ss18": "Stylistic Set 18",
	"ss19": "Stylistic Set 19",
	"ss20": "Stylistic Set 20",
	"subs": "Subscript",
	"sups": "Superscript",
	"swsh": "Swash",
	"titl": "Titling",
	"tjmo": "Trailing Jamo Forms",
	"tnam": "Traditional Name Forms",
	"tnum": "Tabular Figures",
	"trad": "Traditional Forms",
	"twid": "Third Widths",
	"unic": "Unicase",
	"valt": "Alternate Vertical Metrics",
	"vatu": "Vattu Variants",
	"vert": "Vertical Writing",
	"vhal": "Alternate Vertical Half Metrics",
	"vjmo": "Vowel Jamo Forms",
	"vkna": "Vertical Kana Alternates",
	"vkrn": "Vertical Kerning",
	"vpal": "Proportional Alternate Vertical Metrics",
	"vrt2": "Vertical Alternates and Rotation",
	"zero": "Slashed Zero"
}

OTscripts = {
	"__DEFAULT__": "Default",
	"dflt": "Default",
	"DFLT": "Default",

	"arab": "Arabic",
	"armn": "Armenian",
	"bali": "Balinese",
	"beng": "Bengali",
	"bng2": "Bengali v.2",
	"bopo": "Bopomofo",
	"brai": "Braille",
	"bugi": "Buginese",
	"buhd": "Buhid",
	"byzm": "Byzantine Music",
	"cans": "Canadian Syllabics",
	"cari": "Carian",
	"cham": "Cham",
	"cher": "Cherokee",
	"hani": "CJK Ideographic",
	"copt": "Coptic",
	"cprt": "Cypriot Syllabary",
	"cyrl": "Cyrillic",
	"DFLT": "Default",
	"dsrt": "Deseret",
	"deva": "Devanagari",
	"dev2": "Devanagari v.2",
	"ethi": "Ethiopic",
	"geor": "Georgian",
	"glag": "Glagolitic",
	"goth": "Gothic",
	"grek": "Greek",
	"gujr": "Gujarati",
	"gjr2": "Gujarati v.2",
	"guru": "Gurmukhi",
	"gur2": "Gurmukhi v.2",
	"hang": "Hangul",
	"jamo": "Hangul Jamo",
	"hano": "Hanunoo",
	"hebr": "Hebrew",
	"kana": "Hiragana",
	"java": "Javanese",
	"knda": "Kannada",
	"knd2": "Kannada v.2",
	"kana": "Katakana",
	"kali": "Kayah Li",
	"khar": "Kharosthi",
	"khmr": "Khmer",
	"lao": "Lao",
	"latn": "Latin",
	"lepc": "Lepcha",
	"limb": "Limbu",
	"linb": "Linear B",
	"lyci": "Lycian",
	"lydi": "Lydian",
	"mlym": "Malayalam",
	"mlm2": "Malayalam v.2",
	"math": "Mathematical Alphanumeric Symbols",
	"mong": "Mongolian",
	"musc": "Musical Symbols",
	"mymr": "Myanmar",
	"talu": "New Tai Lue",
	"nko": "N'Ko",
	"ogam": "Ogham",
	"olck": "Ol Chiki",
	"ital": "Old Italic",
	"xpeo": "Old Persian Cuneiform",
	"orya": "Oriya",
	"ory2": "Oriya v.2",
	"osma": "Osmanya",
	"phag": "Phags-pa",
	"phnx": "Phoenician",
	"rjng": "Rejang",
	"runr": "Runic",
	"saur": "Saurashtra",
	"shaw": "Shavian",
	"sinh": "Sinhala",
	"xsux": "Sumero-Akkadian Cuneiform",
	"sund": "Sundanese",
	"sylo": "Syloti Nagri",
	"syrc": "Syriac",
	"tglg": "Tagalog",
	"tagb": "Tagbanwa",
	"tale": "Tai Le",
	"taml": "Tamil",
	"tml2": "Tamil v.2",
	"telu": "Telugu",
	"tel2": "Telugu v.2",
	"thaa": "Thaana",
	"thai": "Thai",
	"tibt": "Tibetan",
	"tfng": "Tifinagh",
	"ugar": "Ugaritic Cuneiform",
	"vai": "Vai",
	"yi": "Yi"
}

OTlanguages = {
	"__DEFAULT__": "Default",
	"dflt": "Default",
	"DFLT": "Default",

	"ABA": "Abaza",
	"ABK": "Abkhazian",
	"ADY": "Adyghe",
	"AFK": "Afrikaans",
	"AFR": "Afar",
	"AGW": "Agaw",
	"ALS": "Alsatian",
	"ALT": "Altai",
	"AMH": "Amharic",
	"APPH": "Phonetic transcription-Americanist conventions",
	"ARA": "Arabic",
	"ARI": "Aari",
	"ARK": "Arakanese",
	"ASM": "Assamese",
	"ATH": "Athapaskan",
	"AVR": "Avar",
	"AWA": "Awadhi",
	"AYM": "Aymara",
	"AZE": "Azeri",
	"BAD": "Badaga",
	"BAG": "Baghelkhandi",
	"BAL": "Balkar",
	"BAU": "Baule",
	"BBR": "Berber",
	"BCH": "Bench",
	"BCR": "Bible Cree",
	"BEL": "Belarussian",
	"BEM": "Bemba",
	"BEN": "Bengali",
	"BGR": "Bulgarian",
	"BHI": "Bhili",
	"BHO": "Bhojpuri",
	"BIK": "Bikol",
	"BIL": "Bilen",
	"BKF": "Blackfoot",
	"BLI": "Balochi",
	"BLN": "Balante",
	"BLT": "Balti",
	"BMB": "Bambara",
	"BML": "Bamileke",
	"BOS": "Bosnian",
	"BRE": "Breton",
	"BRH": "Brahui",
	"BRI": "Braj Bhasha",
	"BRM": "Burmese",
	"BSH": "Bashkir",
	"BTI": "Beti",
	"CAT": "Catalan",
	"CEB": "Cebuano",
	"CHE": "Chechen",
	"CHG": "Chaha Gurage",
	"CHH": "Chattisgarhi",
	"CHI": "Chichewa",
	"CHK": "Chukchi",
	"CHP": "Chipewyan",
	"CHR": "Cherokee",
	"CHU": "Chuvash",
	"CMR": "Comorian",
	"COP": "Coptic",
	"COS": "Corsican",
	"CRE": "Cree",
	"CRR": "Carrier",
	"CRT": "Crimean Tatar",
	"CSL": "Church Slavonic",
	"CSY": "Czech",
	"DAN": "Danish",
	"DAR": "Dargwa",
	"DCR": "Woods Cree",
	"DEU": "German",
	"DGR": "Dogri",
	"DHV (deprecated)": "Dhivehi",
	"DIV": "Dhivehi",
	"DJR": "Djerma",
	"DNG": "Dangme",
	"DNK": "Dinka",
	"DRI": "Dari",
	"DUN": "Dungan",
	"DZN": "Dzongkha",
	"EBI": "Ebira",
	"ECR": "Eastern Cree",
	"EDO": "Edo",
	"EFI": "Efik",
	"ELL": "Greek",
	"ENG": "English",
	"ERZ": "Erzya",
	"ESP": "Spanish",
	"ETI": "Estonian",
	"EUQ": "Basque",
	"EVK": "Evenki",
	"EVN": "Even",
	"EWE": "Ewe",
	"FAN": "French Antillean",
	"FAR": "Farsi",
	"FIN": "Finnish",
	"FJI": "Fijian",
	"FLE": "Flemish",
	"FNE": "Forest Nenets",
	"FON": "Fon",
	"FOS": "Faroese",
	"FRA": "French",
	"FRI": "Frisian",
	"FRL": "Friulian",
	"FTA": "Futa",
	"FUL": "Fulani",
	"GAD": "Ga",
	"GAE": "Gaelic",
	"GAG": "Gagauz",
	"GAL": "Galician",
	"GAR": "Garshuni",
	"GAW": "Garhwali",
	"GEZ": "Ge'ez",
	"GIL": "Gilyak",
	"GMZ": "Gumuz",
	"GON": "Gondi",
	"GRN": "Greenlandic",
	"GRO": "Garo",
	"GUA": "Guarani",
	"GUJ": "Gujarati",
	"HAI": "Haitian",
	"HAL": "Halam",
	"HAR": "Harauti",
	"HAU": "Hausa",
	"HAW": "Hawaiin",
	"HBN": "Hammer-Banna",
	"HIL": "Hiligaynon",
	"HIN": "Hindi",
	"HMA": "High Mari",
	"HND": "Hindko",
	"HO": "Ho",
	"HRI": "Harari",
	"HRV": "Croatian",
	"HUN": "Hungarian",
	"HYE": "Armenian",
	"IBO": "Igbo",
	"IJO": "Ijo",
	"ILO": "Ilokano",
	"IND": "Indonesian",
	"ING": "Ingush",
	"INU": "Inuktitut",
	"IPPH": "Phonetic transcription-IPA conventions",
	"IRI": "Irish",
	"IRT": "Irish Traditional",
	"ISL": "Icelandic",
	"ISM": "Inari Sami",
	"ITA": "Italian",
	"IWR": "Hebrew",
	"JAV": "Javanese",
	"JII": "Yiddish",
	"JAN": "Japanese",
	"JUD": "Judezmo",
	"JUL": "Jula",
	"KAB": "Kabardian",
	"KAC": "Kachchi",
	"KAL": "Kalenjin",
	"KAN": "Kannada",
	"KAR": "Karachay",
	"KAT": "Georgian",
	"KAZ": "Kazakh",
	"KEB": "Kebena",
	"KGE": "Khutsuri Georgian",
	"KHA": "Khakass",
	"KHK": "Khanty-Kazim",
	"KHM": "Khmer",
	"KHS": "Khanty-Shurishkar",
	"KHV": "Khanty-Vakhi",
	"KHW": "Khowar",
	"KIK": "Kikuyu",
	"KIR": "Kirghiz",
	"KIS": "Kisii",
	"KKN": "Kokni",
	"KLM": "Kalmyk",
	"KMB": "Kamba",
	"KMN": "Kumaoni",
	"KMO": "Komo",
	"KMS": "Komso",
	"KNR": "Kanuri",
	"KOD": "Kodagu",
	"KOH": "Korean Old Hangul",
	"KOK": "Konkani",
	"KON": "Kikongo",
	"KOP": "Komi-Permyak",
	"KOR": "Korean",
	"KOZ": "Komi-Zyrian",
	"KPL": "Kpelle",
	"KRI": "Krio",
	"KRK": "Karakalpak",
	"KRL": "Karelian",
	"KRM": "Karaim",
	"KRN": "Karen",
	"KRT": "Koorete",
	"KSH": "Kashmiri",
	"KSI": "Khasi",
	"KSM": "Kildin Sami",
	"KUI": "Kui",
	"KUL": "Kulvi",
	"KUM": "Kumyk",
	"KUR": "Kurdish",
	"KUU": "Kurukh",
	"KUY": "Kuy",
	"KYK": "Koryak",
	"LAD": "Ladin",
	"LAH": "Lahuli",
	"LAK": "Lak",
	"LAM": "Lambani",
	"LAO": "Lao",
	"LAT": "Latin",
	"LAZ": "Laz",
	"LCR": "L-Cree",
	"LDK": "Ladakhi",
	"LEZ": "Lezgi",
	"LIN": "Lingala",
	"LMA": "Low Mari",
	"LMB": "Limbu",
	"LMW": "Lomwe",
	"LSB": "Lower Sorbian",
	"LSM": "Lule Sami",
	"LTH": "Lithuanian",
	"LTZ": "Luxembourgish",
	"LUB": "Luba",
	"LUG": "Luganda",
	"LUH": "Luhya",
	"LUO": "Luo",
	"LVI": "Latvian",
	"MAJ": "Majang",
	"MAK": "Makua",
	"MAL": "Malayalam Traditional",
	"MAN": "Mansi",
	"MAP": "Mapudungun",
	"MAR": "Marathi",
	"MAW": "Marwari",
	"MBN": "Mbundu",
	"MCH": "Manchu",
	"MCR": "Moose Cree",
	"MDE": "Mende",
	"MEN": "Me'en",
	"MIZ": "Mizo",
	"MKD": "Macedonian",
	"MLE": "Male",
	"MLG": "Malagasy",
	"MLN": "Malinke",
	"MLR": "Malayalam Reformed",
	"MLY": "Malay",
	"MND": "Mandinka",
	"MNG": "Mongolian",
	"MNI": "Manipuri",
	"MNK": "Maninka",
	"MNX": "Manx Gaelic",
	"MOH": "Mohawk",
	"MOK": "Moksha",
	"MOL": "Moldavian",
	"MON": "Mon",
	"MOR": "Moroccan",
	"MRI": "Maori",
	"MTH": "Maithili",
	"MTS": "Maltese",
	"MUN": "Mundari",
	"NAG": "Naga-Assamese",
	"NAN": "Nanai",
	"NAS": "Naskapi",
	"NCR": "N-Cree",
	"NDB": "Ndebele",
	"NDG": "Ndonga",
	"NEP": "Nepali",
	"NEW": "Newari",
	"NGR": "Nagari",
	"NHC": "Norway House Cree",
	"NIS": "Nisi",
	"NIU": "Niuean",
	"NKL": "Nkole",
	"NKO": "N'Ko",
	"NLD": "Dutch",
	"NOG": "Nogai",
	"NOR": "Norwegian",
	"NSM": "Northern Sami",
	"NTA": "Northern Tai",
	"NTO": "Esperanto",
	"NYN": "Nynorsk",
	"OCI": "Occitan",
	"OCR": "Oji-Cree",
	"OJB": "Ojibway",
	"ORI": "Oriya",
	"ORO": "Oromo",
	"OSS": "Ossetian",
	"PAA": "Palestinian Aramaic",
	"PAL": "Pali",
	"PAN": "Punjabi",
	"PAP": "Palpa",
	"PAS": "Pashto",
	"PGR": "Polytonic Greek",
	"PIL": "Filipino",
	"PLG": "Palaung",
	"PLK": "Polish",
	"PRO": "Provencal",
	"PTG": "Portuguese",
	"QIN": "Chin",
	"RAJ": "Rajasthani",
	"RCR": "R-Cree",
	"RBU": "Russian Buriat",
	"RIA": "Riang",
	"RMS": "Rhaeto-Romanic",
	"ROM": "Romanian",
	"ROY": "Romany",
	"RSY": "Rusyn",
	"RUA": "Ruanda",
	"RUS": "Russian",
	"SAD": "Sadri",
	"SAN": "Sanskrit",
	"SAT": "Santali",
	"SAY": "Sayisi",
	"SEK": "Sekota",
	"SEL": "Selkup",
	"SGO": "Sango",
	"SHN": "Shan",
	"SIB": "Sibe",
	"SID": "Sidamo",
	"SIG": "Silte Gurage",
	"SKS": "Skolt Sami",
	"SKY": "Slovak",
	"SLA": "Slavey",
	"SLV": "Slovenian",
	"SML": "Somali",
	"SMO": "Samoan",
	"SNA": "Sena",
	"SND": "Sindhi",
	"SNH": "Sinhalese",
	"SNK": "Soninke",
	"SOG": "Sodo Gurage",
	"SOT": "Sotho",
	"SQI": "Albanian",
	"SRB": "Serbian",
	"SRK": "Saraiki",
	"SRR": "Serer",
	"SSL": "South Slavey",
	"SSM": "Southern Sami",
	"SUR": "Suri",
	"SVA": "Svan",
	"SVE": "Swedish",
	"SWA": "Swadaya Aramaic",
	"SWK": "Swahili",
	"SWZ": "Swazi",
	"SXT": "Sutu",
	"SYR": "Syriac",
	"TAB": "Tabasaran",
	"TAJ": "Tajiki",
	"TAM": "Tamil",
	"TAT": "Tatar",
	"TCR": "TH-Cree",
	"TEL": "Telugu",
	"TGN": "Tongan",
	"TGR": "Tigre",
	"TGY": "Tigrinya",
	"THA": "Thai",
	"THT": "Tahitian",
	"TIB": "Tibetan",
	"TKM": "Turkmen",
	"TMN": "Temne",
	"TNA": "Tswana",
	"TNE": "Tundra Nenets",
	"TNG": "Tonga",
	"TOD": "Todo",
	"TRK": "Turkish",
	"TSG": "Tsonga",
	"TUA": "Turoyo Aramaic",
	"TUL": "Tulu",
	"TUV": "Tuvin",
	"TWI": "Twi",
	"UDM": "Udmurt",
	"UKR": "Ukrainian",
	"URD": "Urdu",
	"USB": "Upper Sorbian",
	"UYG": "Uyghur",
	"UZB": "Uzbek",
	"VEN": "Venda",
	"VIT": "Vietnamese",
	"WA": "Wa",
	"WAG": "Wagdi",
	"WCR": "West-Cree",
	"WEL": "Welsh",
	"WLF": "Wolof",
	"XBD": "Tai Lue",
	"XHS": "Xhosa",
	"YAK": "Yakut",
	"YBA": "Yoruba",
	"YCR": "Y-Cree",
	"YIC": "Yi Classic",
	"YIM": "Yi Modern",
	"ZHH": "Chinese Hong Kong",
	"ZHP": "Chinese Phonetic",
	"ZHS": "Chinese Simplified",
	"ZHT": "Chinese Traditional",
	"ZND": "Zande",
	"ZUL": "Zulu"
}

OTbaselines = {
	"hang": "The hanging baseline. This is the horizontal line from which syllables seem to hang in Tibetan script.",
	"icfb": "Ideographic character face bottom edge baseline.",
	"icft": "Ideographic character face top edge baseline. ",
	"ideo": "Ideographic em-box bottom edge baseline. ",
	"idtp": "Ideographic em-box top edge baseline.",
	"math": "The baseline about which mathematical characters are centered.",
	"romn": "The baseline used by simple alphabetic scripts such as Latin, Cyrillic and Greek."
}
